# Generated by Django 4.2.7 on 2023-11-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "merchant_id",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                ("amount", models.IntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("notes", models.JSONField(blank=True, null=True)),
                ("identifier", models.CharField(blank=True, max_length=100, null=True)),
                ("attempts", models.IntegerField(default=0)),
                ("amount_due", models.IntegerField(blank=True)),
                ("amount_paid", models.IntegerField(blank=True)),
                ("partial_payment", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("attempted", "Attempted"),
                            ("paid", "Paid"),
                        ],
                        default="created",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "orders",
            },
        ),
    ]
