# Generated by Django 4.2.7 on 2023-11-08 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Key",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("secret", models.CharField(blank=True, max_length=100)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("main", "Main"), ("sandbox", "Sandbox")],
                        max_length=10,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keys",
                        to="db.merchant",
                    ),
                ),
            ],
            options={
                "db_table": "keys",
            },
        ),
    ]
